select * from mytable limit (20);

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    item_purchased,
    purchase_amount,
    discount_applied
FROM mytable
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM mytable
  )
ORDER BY purchase_amount DESC;

--03. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "average_rating"
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;

--4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM mytable
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY average_spend DESC;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
  item_purchased,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number ofprevious purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases <= 2 THEN 'New'
        WHEN previous_purchases <= 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    
    COUNT(*) AS customer_count

FROM mytable

GROUP BY
    CASE
        WHEN previous_purchases <= 2 THEN 'New'
        WHEN previous_purchases <= 5 THEN 'Returning'
        ELSE 'Loyal'
    END

ORDER BY customer_count DESC;
--Q8. What are the top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM mytable
    GROUP BY category, item_purchased
),

ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        RANK() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)

SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, purchase_count DESC;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type,

    COUNT(*) AS total_customers,

    SUM(
        CASE
            WHEN subscription_status = 'Yes' THEN 1
            ELSE 0
        END
    ) AS subscribed_customers,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN subscription_status = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS subscription_percentage

FROM mytable

GROUP BY
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END;
--Q10. What is the revenue contribution of each age group?
WITH age_groups AS (
    SELECT
        CASE
            WHEN age BETWEEN 18 AND 25 THEN '18-25'
            WHEN age BETWEEN 26 AND 35 THEN '26-35'
            WHEN age BETWEEN 36 AND 45 THEN '36-45'
            WHEN age BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END AS age_group,

        purchase_amount

    FROM mytable
)

SELECT
    age_group,

    SUM(purchase_amount) AS total_revenue,

    ROUND(
        100.0 * SUM(purchase_amount)
        / SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_contribution_percentage

FROM age_groups

GROUP BY age_group

ORDER BY total_revenue DESC;